permissions:
  visibility: "reframe.toggle.visibility"
  fixation: "reframe.toggle.fixation"
phrases:
  menu: "Menu"
  visibility: "§fVisibility"
  visible: "§aVisible"
  invisible: "§cInvisible"
  fixation: "§fFixation"
  fixed: "§aFixed"
  unfixed: "§cUnfixed"