permission: "reframe.use"
phrases:
  menu: "Menu"
  visibility: "§fVisibility"
  visible: "§aVisible"
  invisible: "§cInvisible"
  fixation: "§fFixation"
  fixed: "§aFixed"
  unfixed: "§cUnfixed"
  functions: "Functions"
  button-simulation: "§fButton Simulation"